# **Regra de Cramer: Análise e Implementação**
A Regra de Cramer é um método direto da álgebra linear utilizado para resolver sistemas de equações lineares. Embora não seja o método mais eficiente para sistemas grandes, possui grande valor teórico e é muito prático para sistemas pequenos.

##**Ideia Central:**
A ideia central do método é que a solução de um sistema linear quadrado Ax = b pode ser encontrada através de uma fórmula explícita que envolve determinantes. Para encontrar o valor de cada incógnita x_i, calcula-se a razão entre dois determinantes:

O denominador é o determinante da matriz principal dos coeficientes, det(A).

O numerador é o determinante de uma matriz modificada, A_i, onde a i-ésima coluna de A é substituída pelo vetor de termos independentes b.

##**Entrada e Saída:**

**Entrada:**

*   **A:** Uma matriz de coeficientes quadrada (n x n).
*   **b:** Um vetor coluna (n x 1) com os termos independentes.

**Saída:**

*   **x:** O vetor coluna (n x 1) que representa a solução única do sistema.


##**Tipo do Método:**
É um método direto, o que significa que ele fornece a solução exata em um número finito de passos, sem a necessidade de aproximações iterativas.

##**Requisitos para Uso:**

O sistema de equações precisa ser quadrado, ou seja, o número de equações deve ser igual ao número de incógnitas. O sistema deve ter uma solução única.

##**Propriedades da Matriz de Coeficientes (A):**

**Singularidade:** A matriz "A" precisa ser não singular, o que é a condição fundamental para a aplicação do método. Uma matriz não singular é aquela cujo determinante é diferente de zero.

**Simetria:** A matriz "A" não precisa ser simétrica.

**Positiva Definida:** A matriz "A" não precisa ser positiva definida.



In [1]:
# Importando a biblioteca NumPy
import numpy as np

def regra_de_cramer(A, b):
    """
    Resolve um sistema de equações lineares Ax = b usando a Regra de Cramer.

    Argumentos:
    A (np.ndarray): Matriz de coeficientes (deve ser quadrada).
    b (np.ndarray): Vetor de termos independentes.

    Retorna:
    np.ndarray: O vetor solução x, se a solução for única.
    str: Uma mensagem de erro se o sistema não tiver solução única.
    """
    # Verifica se a matriz A é quadrada
    if A.shape[0] != A.shape[1]:
        return "Erro: A matriz dos coeficientes não é quadrada."

    # Calcula o determinante da matriz de coeficientes A
    det_A = np.linalg.det(A)

    # Verifica se o sistema tem uma solução única (determinante != 0)
    if det_A == 0:
        return "O sistema não possui solução única (determinante da matriz principal é zero)."

    # Obtém o número de incógnitas do sistema
    n = A.shape[0]

    # Inicializa o vetor solução x com zeros
    x = np.zeros(n)

    # Itera sobre cada incógnita para encontrar seu valor
    for i in range(n):
        # Cria uma cópia da matriz A para modificação
        Ai = A.copy()

        # Substitui a i-ésima coluna de Ai pelo vetor b
        Ai[:, i] = b

        # Calcula o determinante da matriz modificada Ai
        det_Ai = np.linalg.det(Ai)

        # Calcula o valor da incógnita xi usando a fórmula de Cramer
        x[i] = det_Ai / det_A

    return x

# --- Exemplo de Uso Prático ---

# Sistema de equações:
# 2x + 1y - 1z = 8
# -3x - 1y + 2z = -11
# -2x + 1y + 2z = -3

# Definição da Matriz de coeficientes A
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
], dtype=float) # Usar float para evitar problemas de tipo

# Definição do Vetor de termos independentes b
b = np.array([8, -11, -3], dtype=float)

# Chamada da função para resolver o sistema
solucao = regra_de_cramer(A, b)

# Apresentação dos resultados
print("--- RESOLVENDO O SISTEMA AX = B ---")
print(f"Matriz de coeficientes A:\n{A}\n")
print(f"Vetor de termos independentes b:\n{b}\n")
print(f"Solução do sistema (x, y, z): {solucao}")

# Verificação da solução
# Se Ax = b está correto, então Ax - b deve ser um vetor de zeros (ou muito próximo disso).
print(f"\nVerificação do resultado (A * x - b):\n{np.dot(A, solucao) - b}")

--- RESOLVENDO O SISTEMA AX = B ---
Matriz de coeficientes A:
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]

Vetor de termos independentes b:
[  8. -11.  -3.]

Solução do sistema (x, y, z): [ 2.  3. -1.]

Verificação do resultado (A * x - b):
[-5.32907052e-15  8.88178420e-15  5.32907052e-15]


In [2]:
# Importando as bibliotecas necessárias
import numpy as np
from scipy import linalg

def resolver_com_scipy(A, b):
    """
    Resolve um sistema de equações lineares Ax = b usando as funções da SciPy,
    após verificar a condição da Regra de Cramer (determinante não nulo).

    Argumentos:
    A (np.ndarray): Matriz de coeficientes (deve ser quadrada).
    b (np.ndarray): Vetor de termos independentes.

    Retorna:
    np.ndarray: O vetor solução x, se a solução for única.
    str: Uma mensagem de erro se o sistema não tiver solução única.
    """
    # Tenta calcular o determinante usando SciPy
    try:
        det_A = linalg.det(A)
    except ValueError:
        return "Erro: A entrada não é uma matriz quadrada."

    # Verifica a condição principal da Regra de Cramer
    # Usamos np.isclose para comparar com zero de forma segura com números de ponto flutuante
    if np.isclose(det_A, 0):
        return "O sistema não possui solução única (determinante é zero)."

    # Se a condição for satisfeita, resolve o sistema usando a função otimizada da SciPy
    try:
        x = linalg.solve(A, b)
        return x
    except linalg.LinAlgError:
        # Esta exceção é capturada caso a matriz seja singular, embora o det já tenha verificado.
        return "Erro de Álgebra Linear: A matriz é singular."

# --- Exemplo de Uso Prático (o mesmo sistema anterior) ---

# Sistema de equações:
# 2x + 1y - 1z = 8
# -3x - 1y + 2z = -11
# -2x + 1y + 2z = -3

# Definição da Matriz de coeficientes A
A = np.array([
    [2, 1, -1],
    [-3, -1, 2],
    [-2, 1, 2]
], dtype=float)

# Definição do Vetor de termos independentes b
b = np.array([8, -11, -3], dtype=float)


# Chamada da função para resolver o sistema
print("--- RESOLVENDO O SISTEMA COM SCIPY ---")
solucao_scipy = resolver_com_scipy(A, b)


# Apresentação dos resultados
print(f"Matriz de coeficientes A:\n{A}\n")
print(f"Vetor de termos independentes b:\n{b}\n")
print(f"Solução do sistema (x, y, z): {solucao_scipy}")

# Verificação da solução
# A verificação np.allclose é mais robusta para computação numérica que a comparação direta
# Ela verifica se A @ x é "próximo o suficiente" de b.
print(f"\nSolução é correta? {np.allclose(A @ solucao_scipy, b)}")

--- RESOLVENDO O SISTEMA COM SCIPY ---
Matriz de coeficientes A:
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]

Vetor de termos independentes b:
[  8. -11.  -3.]

Solução do sistema (x, y, z): [ 2.  3. -1.]

Solução é correta? True


##**Qualidades e Vantagens**
**Fórmula Explícita**: Fornece uma expressão direta para a solução, o que é de grande valor teórico e útil em demonstrações matemáticas.

**Ideal para Sistemas Pequenos**: Para sistemas 2x2 e 3x3, é um método rápido, elegante e fácil de aplicar manualmente ou com código simples.

**Cálculo de uma Única Variável**: Se o objetivo for encontrar o valor de apenas uma incógnita, não é necessário resolver o sistema inteiro.

##**Quando o Método Falha?**
O método falha quando o determinante da matriz dos coeficientes é zero (det(A)=0). Isso indica que o sistema ou não tem solução, ou tem infinitas soluções. A Regra de Cramer não consegue diferenciar entre esses dois casos.

## **É Considerado Eficiente?**
**Não**. Para sistemas de ordem maior, é um método extremamente ineficiente. O cálculo de determinantes tem um custo computacional muito alto (complexidade de tempo O(n!)), que cresce muito mais rápido que outros métodos, como a Eliminação de Gauss (complexidade O(n³)). Isso o torna impraticável para aplicações numéricas em problemas de grande escala.

## Conclusão
A Regra de Cramer é uma boa ferramenta do ponto de vista teórico e uma excelente escolha para resolver sistemas lineares pequenos (2x2 e 3x3). Sua fórmula é direta e oferece uma clareza conceitual sobre a natureza da solução.

No entanto, devido à sua alta complexidade computacional, ela não é recomendada para a resolução de sistemas grandes em aplicações práticas, onde métodos como a Eliminação de Gauss ou a Decomposição LU são vastamente superiores em performance.

##Referências:

*   A inteligência artificial Gemini.
*   Videos no Youtube do Canal Thadeu Penna.

